In [2]:
x = 1
y = -100
type(x)


int

In [4]:
3//2

1

In [5]:
3/2

1.5

In [6]:
2**2

4

In [7]:
print(100**100)

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000


In [8]:
a = 3+2j
b = 3-2j
a+b

(6+0j)

In [10]:
a*b

(13+0j)

In [11]:
a.conjugate()

(3-2j)

In [12]:
abs(-10)

10

In [13]:
print('''arif is 
a boy ''')

arif is 
a boy 


In [14]:
a = "cat"
a[0]

'c'

In [15]:
a[-2]

'a'

In [16]:
a[-1]

't'

In [17]:
a = "data"
a[1:3]

'at'

In [18]:
a[:]

'data'

In [19]:
a[1:]

'ata'

In [20]:
str = "Hello Avengers"
print(str[1::2])

el vnes


In [21]:
len(str)

14

In [22]:
str.lower()

'hello avengers'

In [23]:
str.upper()

'HELLO AVENGERS'

In [25]:
str.count("s")

1

In [26]:
a = "1234"
print(a.isdigit())

True


In [27]:
"1" in a

True

In [31]:
string1 = "Data#Avengers#"
for i in string1:
    if i =='#':
      print(,end='')
        

##

In [34]:
for i in range(len(string1)):
    if string1[i]=="#":
        print(i,end="\n")

4
13


In [35]:
list1 = [1,2,3,4]

In [36]:
list1 = list([1,2])

In [37]:
list1

[1, 2]

In [38]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]

In [52]:
list1[1][2]

6

In [53]:
list1*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [55]:
import numpy as np

In [56]:
arr1 = np.array([1,2,3])

In [57]:
arr1

array([1, 2, 3])

In [58]:
print(np.eye(3,5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [3]:
print("arif")

arif


In [1]:
str = 'Hellow World'
str.find('W')

7

In [5]:
'World' in str

True

In [7]:
bool(4.8)

True

In [9]:
str1 = "Data Avengers"

In [11]:
str1.find('#')

-1

In [19]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [21]:
type(None)

NoneType

In [23]:
None ==False

False

In [25]:
l1 = [1,2,3,4]
print(l1)

[1, 2, 3, 4]


In [27]:
l1.append(3)

In [29]:
l1

[1, 2, 3, 4, 3]

In [31]:
l1.pop()

3

In [33]:
l1

[1, 2, 3, 4]

In [35]:
l1.pop(0)

1

In [37]:
l1

[2, 3, 4]

In [43]:
sum(l1)

9

In [47]:
sorted(l1,reverse=True)

[4, 3, 2]

In [49]:
l1 = [1,2,3,4]
l2 = l1.extend([5,6,7])

In [53]:
l1

[1, 2, 3, 4, 5, 6, 7]

In [61]:
str = "Hi i am arif"
l1 = str.split()
" ".join(l1)

'Hi i am arif'

In [69]:
2,

(2,)

In [73]:
tuple("abc")

('a', 'b', 'c')

In [75]:
list("abc")

['a', 'b', 'c']

In [77]:
set("abc")

{'a', 'b', 'c'}

In [91]:
q = (1,2,3)
a,b,c = q

In [97]:
q+(2,3,4)

(1, 2, 3, 2, 3, 4)

In [99]:
student = {'name':["Arif","Shinchan"],
          'Marks':[23,12,44]}

In [111]:
student.values()

dict_values([['Arif', 'Shinchan'], [23, 12, 44]])

In [113]:
student.pop("Marks")

[23, 12, 44]

In [115]:
student

{'name': ['Arif', 'Shinchan']}

In [179]:
list1 = [x for x in range(1,10) if x%2==0]

In [181]:
list1

[2, 4, 6, 8]

In [159]:
list1 = [char.upper() for char in "DataAvengers"]

In [161]:
list1

['D', 'A', 'T', 'A', 'A', 'V', 'E', 'N', 'G', 'E', 'R', 'S']

In [163]:
list2 = ['Python','Sql','Statistics']
list1 = [i[0].upper() for i in list2]

In [165]:
list1

['P', 'S', 'S']

In [183]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
[j  for i in list2 for j in i if j >4]

[5, 6, 7, 8, 9]

In [189]:
set1 = set()
set1.add(4)

In [191]:
set1

{4}

In [197]:
set1.add(5)

In [199]:
set1

{4, 5}

In [207]:
for i in set1:
    print (i)

4
5


In [211]:
dict1 = {i:i*i for i in range(1,11)}

In [215]:
dict1

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [219]:
dic2 = {1:'Python',2:"SQL",3:"Statistics"}
for key,value in dic2.items():
    print((key,value))

dict2 = {value:key for key,value in dic2.items()}

(1, 'Python')
(2, 'SQL')
(3, 'Statistics')


In [221]:
dict2

{'Python': 1, 'SQL': 2, 'Statistics': 3}

In [223]:
dict3 = {i:{i*i:i*i*i} for i in range(1,15)}

In [225]:
dict3

{1: {1: 1},
 2: {4: 8},
 3: {9: 27},
 4: {16: 64},
 5: {25: 125},
 6: {36: 216},
 7: {49: 343},
 8: {64: 512},
 9: {81: 729},
 10: {100: 1000},
 11: {121: 1331},
 12: {144: 1728},
 13: {169: 2197},
 14: {196: 2744}}